changelog:
  categories:
    - title: "Features"
      labels: ["feature", "enhancement"]
    - title: "Bug Fixes"
      labels: ["bug", "fix"]
    - title: "Maintenance"
      labels: ["chore", "refactor", "build"]
    - title: "Docs"
      labels: ["docs"]
